//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLoggerWithWebReporting {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        private Gadgeteer.Modules.GHIElectronics.UsbClientDP usbClientDP;
        
        private Gadgeteer.Modules.GHIElectronics.Button button;
        
        private Gadgeteer.Modules.GHIElectronics.MulticolorLed multicolorLed;
        
        private Gadgeteer.Modules.GHIElectronics.Distance_US3 distance_US3;
        
        private Gadgeteer.Modules.GHIElectronics.WiFi_RS21 wifi_RS21;
        
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZSpider();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.usbClientDP = new GTM.GHIElectronics.UsbClientDP(1);
            this.multicolorLed = new GTM.GHIElectronics.MulticolorLed(4);
            this.distance_US3 = new GTM.GHIElectronics.Distance_US3(5);
            this.button = new GTM.GHIElectronics.Button(8);
            this.wifi_RS21 = new GTM.GHIElectronics.WiFi_RS21(9);
        }
    }
}
